<?php

# Guard Towers
DEFINE('GUARD_TOWER_MAX',0.35);
DEFINE('GUARD_TOWER_MULTIPLIER',1.75);

# Gryphon Nests
DEFINE('GRYPHON_NEST_MAX',0.35);
DEFINE('GRYPHON_NEST_MULTIPLIER',1.75);

# Temples
DEFINE('TEMPLE_MAX',0.25);
DEFINE('TEMPLE_MULTIPLIER',1.50);

# Tech OP bonuses
DEFINE('MILITARY_GENIUS',0.05);
DEFINE('MAGICAL_WEAPONRY',0.10);